from peppi_py import read_slippi, read_peppi
from pprint import pprint

game = read_slippi('src\data\Game_20241125T235046.slp')
pprint(game.start.stage)
print(game.frames.ports[1].leader.pre.random_seed)
print(game.frames.ports[1].leader.pre.state)
print(game.frames.ports[1].leader.pre.position.x)
print(game.frames.ports[1].leader.pre.position.y)
print(game.frames.ports[1].leader.pre.direction)
print(game.frames.ports[1].leader.pre.joystick.x)
print(game.frames.ports[1].leader.pre.joystick.y)
print(game.frames.ports[1].leader.pre.cstick.x)
print(game.frames.ports[1].leader.pre.cstick.y)
print(game.frames.ports[1].leader.pre.triggers)
print(game.frames.ports[1].leader.pre.buttons)
print(game.frames.ports[1].leader.pre.buttons_physical)
print(game.frames.ports[1].leader.pre.triggers_physical.l)
print(game.frames.ports[1].leader.pre.triggers_physical.r)
print(game.frames.ports[1].leader.pre.raw_analog_x)
print(game.frames.ports[1].leader.pre.raw_analog_y)
print(game.frames.ports[1].leader.pre.percent)
print(game.frames.ports[1].leader.post.character)
print(game.frames.ports[1].leader.post.state)
print(game.frames.ports[1].leader.post.position.x)
print(game.frames.ports[1].leader.post.position.y)
print(game.frames.ports[1].leader.post.direction)
print(game.frames.ports[1].leader.post.percent)
print(game.frames.ports[1].leader.post.shield)
print(game.frames.ports[1].leader.post.last_attack_landed)
print(game.frames.ports[1].leader.post.combo_count)
print(game.frames.ports[1].leader.post.last_hit_by)
print(game.frames.ports[1].leader.post.stocks)
print(game.frames.ports[1].leader.post.state_age)
print(game.frames.ports[1].leader.post.state_flags)
print(game.frames.ports[1].leader.post.misc_as)
print(game.frames.ports[1].leader.post.airborne)
print(game.frames.ports[1].leader.post.ground)
print(game.frames.ports[1].leader.post.jumps)
print(game.frames.ports[1].leader.post.l_cancel)
print(game.frames.ports[1].leader.post.hurtbox_state)
print(game.frames.ports[1].leader.post.velocities.self_x_air)
print(game.frames.ports[1].leader.post.velocities.self_y)
print(game.frames.ports[1].leader.post.velocities.knockback_x)
print(game.frames.ports[1].leader.post.velocities.knockback_y)
print(game.frames.ports[1].leader.post.velocities.self_x_ground)
print(game.frames.ports[1].leader.post.hitlag)
print(game.frames.ports[1].leader.post.animation_index)
print( game.frames.ports[1].leader.pre.random_seed[30])
print(game.start.players[0].netplay.name)
print(game.start.match.id)
import os

folder_path = "src\data"
file_count = len([name for name in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, name))])
print(f"There are {file_count} files in the folder.")